orbs:
  node: circleci/node@4.0.0

version: 2.1

jobs:
  build:
    docker:
      -image: circleci/redis:latest
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
        name: "Run docker redis image"
        command: docker run --name redisdb -p 6379:6379 redis

workflows:
  app-tests:
    jobs:
      - node/test